language: android

env:
  global:
    - GRADLE_OPTS=-Xmx512m

android:
  components:
    - tools
    - platfom-tools
    - build-tools-27.0.3
    - android-26
    - extra-android-m2repository

jdk:
  - oraclejdk8